---
title: ""
output: github_document
---


## 1. Configuración

A continuación se cargan las librerias necesarias


```{r setup, include=FALSE}

# Para renderizar el documento
knitr::opts_chunk$set(echo = TRUE)

# Para cargar librerias se verifica pacman
if ("pacman" %in% installed.packages() == FALSE) install.packages("pacman")

# Se cargan las librerias
pacman::p_load(char = c(
  "here", #manejo de rutas
  "sf", #manipulación de dats espaciales
  "geodata", #carga de SoilGrids
  "terra", #raster data
  "dplyr", #procesamiento de data frames
  "ggplot2",  #graficación
  "wesanderson", #paleta de colores
  "viridis", #paleta colores
  "qs" #escribir y leer rápidamente objetos R
  )
)

```


## 2. Carga

Se carga el límite del área de estudio

```{r carga_departamentos}

# Define ruta y nombre de capa de geopackage de departamentos
deptos_ruta <- here("Data", "INPUT_departamentos_IGAC_Abril_2025.gpkg")
capa_nombre_deptos <- sf::st_layers(deptos_ruta)$name[1]

# Carga geopackage de departamentos
departamentos_sf <- sf::st_read(
  deptos_ruta,
  layer = capa_nombre_deptos,
  quiet = TRUE
  ) |>
  # Se seleccionan 21 departamentos de la zona Andina, Caribe y Pacífica
  dplyr::filter(
    DeNombre %in% c(
    "Antioquia"
    )
  ) |>
  tidyr::drop_na() |>
  sf::st_transform(9377)


# departamento_1_sf pasa de "SHAPE" a "geometry"
names(departamentos_sf)[names(departamentos_sf) == "SHAPE"] <- "geometry"
departamentos_sf <- sf::st_as_sf(as.data.frame(departamentos_sf), sf_column_name = "geometry")

# Se unen los polígonos en uno solo
area_piloto <- sf::st_union(departamentos_sf)

# Buffer de 20 km para evitar edge effects
area_buffer <- sf::st_buffer(area_piloto, 20000)
area_buffer_wgs84 <- st_transform(area_buffer, 4326) # bbox para SoilGrids

```

Se cargan los datos de SoilGrids

```{r carga_SoilGrids}

# Descarga automática y armonizada de variables SoilGrids con geodata
rast_stack <- geodata::soil_grids(
    var = c("clay", "sand", "silt", "ocd", "phh2o", "cec"),  # Ajusta según tus variables
    depth = c("0-5cm", "15-30cm"),  # O usa todas las profundidades si tu RAM lo permite
    path = "soilgrids_data",
    bbox = st_bbox(area_buffer_wgs84), # Bounding box WGS84
    crs = "EPSG:9377",
    r = 250 # resolución estándar SoilGrids
)

# Recorta exactamente al buffer (por si el bbox incluye celdas externas)
rast_stack <- terra::crop(rast_stack, vect(area_buffer))
rast_stack <- terra::mask(rast_stack, vect(area_buffer))

```


